baseURL = "https://www.skycoin.net/blog"
languageCode = "en-us"
title = "Blog"
defaultContentLanguage = "en"

relativeURLs = true
canonifyURLs = true

googleAnalytics = "UA-105234182-1"
#disqusShortname = ""

# hugo-xmin specific variables
theme = "skycoin"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "murphy"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "Explorer"
    identifier = "explorer"
    url = "//explorer.skycoin.net"
    weight = 2
[[menu.main]]
    name = "Wallet"
    identifier = "wallet"
    url = "/downloads/"
    weight = 3
[[menu.main]]
    name = "Team"
    identifier = "team"
    url = "/team/"
    weight = 4
[[menu.main]]
    name = "Ecosystem"
    identifier = "ecosystem"
    url = "/ecosystem/"
    weight = 5        

[author]
  name = "Skycoin"

[params]
  keywords = "skycoin"
  rss = "/index.xml"
  telegram = "https://t.me/Skycoin"
  discord = "https://discord.gg/MTepVHE"
  description = "Skycoin Project Updates"
  email = ""
  github = "skycoin"
  twitter = "skycoinproject"
  twitterAnalytics = "ny03t"

[[params.social]]
  name = "Medium"
  url = "/"
  image = "images/medium.svg"
[[params.social]]
  name = "Twitter"
  url = "https://twitter.com/skycoinproject"
  image = "images/twitter.svg"
[[params.social]]
  name = "Facebook"
  url = "https://www.facebook.com/skycoinproject"
  image = "images/facebook.svg"
[[params.social]]
  name = "Instagram"
  url = "https://www.instagram.com/skycoinproject/"
  image = "images/instagram.svg"
[[params.social]]
  name = "Github"
  url = "https://github.com/skycoin/skycoin"
  image = "images/github.svg"
[[params.social]]
  name = "Quora"
  url = "https://www.quora.com/profile/Skycoin-Project/topics"
  image = "images/q.svg"
[[params.social]]
  name = "Youtube"
  url = "https://www.youtube.com/c/Skycoin"
  image = "images/youtube.svg"
[[params.social]]
  name = "Snapchat"
  url = "/"
  image = "images/snapchat.svg"
[[params.social]]
  name = "Reddit"
  url = "https://www.reddit.com/r/SkycoinProject"
  image = "images/reddit.svg"
[[params.social]]
  name = "Apple"
  url = "/"
  image = "images/apple.svg"  
[[params.social]]
  name = "Discord"
  url = "https://discord.gg/MTepVHE"
  image = "images/discord.svg" 
[[params.social]]
  name = "Telegram"
  url = "https://t.me/Skycoin"
  image = "images/telegram.svg"    

[Languages]
[Languages.en]
  weight = -1
  title = "Blog"
  languageName = "English"

[Languages.zh]
  weight = 1
  title = "天空币博客"
  hasCJKLanguage = true
  languageName = "中文"

[Languages.ru]
  weight = 2
  title = "Блог"
  languageName = "Русский"

[Languages.ko]
  weight = 3
  title = "블로그"
  languageName = "한국어"

[Languages.es]
    weight = 4
    title = "Blog"
    languageName = "Español"

[Languages.de]
    weight = 5
    title = "Blog"
    languageName = "Deutsch"

[Languages.ja]
    weight = 6
    title = "Blog"
    languageName = "日本語"

[Languages.el]
    weight = 7
    title = "Blog"
    languageName = "Ελληνικά"

[Languages.fr]
    weight = 8
    title = "Blog"
    languageName = "Français"

[Languages.pt]
    weight = 9
    title = "Blog"
    languageName = "Português"

[Languages.it]
    weight = 10
    title = "Blog"
    languageName = "Italiano"

[[menu.languages]]
  name = "English"
  weight = -1
  url = "/"
[[menu.languages]]
  name = "中文"
  weight = 1
  url = "/zh/"
[[menu.languages]]
  name = "Русский"
  weight = 2
  url = "/ru/"
[[menu.languages]]
  name = "한국어"
  weight = 3
  url = "/ko/"
# [[menu.languages]]
#   name = "Español"
#   weight = 4
#   url = "/es/"
# [[menu.languages]]
#   name = "Deutsch"
#   weight = 5
#   url = "/de/"
# [[menu.languages]]
#   name = "日本語"
#   weight = 6
#   url = "/ja/"
# [[menu.languages]]
#   name = "Ελληνικά"
#   weight = 7
#   url = "/el/"
# [[menu.languages]]
#   name = "Français"
#   weight = 8
#   url = "/fr/"
# [[menu.languages]]
#   name = "Português"
#   weight = 9
#   url = "/pt/"
# [[menu.languages]]
#   name = "Italiano"
#   weight = 10
#   url = "/it/"
